create database db_erd;
use db_erd;

CREATE TABLE NHACC (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC VARCHAR(100),
    DiaChi VARCHAR(255),
    SDT VARCHAR(15)
);

CREATE TABLE VATTU (
    MaVTU VARCHAR(10) PRIMARY KEY,
    TenVTU VARCHAR(100),
    DGNhap DECIMAL(15,2),
    SLNhap INT,
    DGXuat DECIMAL(15,2),
    SLXuat INT,
    MaNCC VARCHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(10) PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE DONDH (
    SoDH VARCHAR(10) PRIMARY KEY,
    NgayDH DATE
);

CREATE TABLE CT_PHIEUXUAT (
    SoPX VARCHAR(10),
    MaVTU VARCHAR(10),
    SLXuat INT,
    DGXuat DECIMAL(15,2),
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CT_PHIEUNHAP (
    SoPN VARCHAR(10),
    MaVTU VARCHAR(10),
    SLNhap INT,
    DGNhap DECIMAL(15,2),
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CT_DONDH (
    SoDH VARCHAR(10),
    MaVTU VARCHAR(10),
    SoLuongDat INT,
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
